# Generated by Django 5.0.1 on 2026-01-04 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF Document"),
                            ("VIDEO", "Video"),
                            ("LINK", "External Link"),
                            ("NOTES", "Lecture Notes"),
                            ("PYQ", "Previous Year Questions"),
                            ("HANDOUT", "Course Handout"),
                        ],
                        default="PDF",
                        max_length=10,
                    ),
                ),
                (
                    "link",
                    models.URLField(help_text="URL to the resource", max_length=500),
                ),
                ("description", models.TextField(blank=True)),
                ("slug", models.SlugField(blank=True, max_length=250)),
                ("views", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="courses.course",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_resources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource",
                "verbose_name_plural": "Resources",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["course", "type"], name="resources_r_course__2b09e5_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="resources_r_created_83a7af_idx"
                    ),
                ],
            },
        ),
    ]
